plugins {
    id 'java-library'
    id 'io.papermc.paperweight.userdev' version "${paperweight_version}"
    id "xyz.jpenilla.resource-factory-bukkit-convention" version "1.3.0"
}

group = project.maven_group
version = project.mod_version
description = "Trigger Streamer.bot action from in-game!"

repositories {
    mavenCentral()
    maven {
        name = 'papermc'
        url = 'https://repo.papermc.io/repository/maven-public/'
    }
}

dependencies {
    paperweight.paperDevBundle(paper_version)
}

bukkitPluginYaml {
    main = "com.mosadie.streamercraft.StreamerCraft"
    authors.add("MoSadie")
    apiVersion = "1.21.4"
    website = "https://modrinth.com/plugin/streamercraft"
    name = "Streamer.craft"
}