modLoader = "javafml"
loaderVersion = "[4,)"
#issueTrackerURL = ""
license = "GNU LGPL v3"

[[mods]]
modId = "streamercraft"
version = "${version}"
displayName = "Streamer.craft"
authors = "MoSadie"
description = '''
Trigger Streamer.bot action from in-game!
'''
logoFile = "assets/streamercraft/icon.png"

[[dependencies.streamercraft]]
modId = "neoforge"
type = "required"
versionRange = "[21.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.streamercraft]]
modId = "minecraft"
type = "required"
versionRange = "[1.21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.streamercraft]]
modId = "architectury"
type = "required"
versionRange = "[13.0.2,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "streamercraft.mixins.json"
